apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: anithapatcha/go-web-app:latest
        ports:
        - containerPort: 9000
