apiVersion: v1
kind: Service
metadata:
  name: go-web-service
  labels:
    app: web
spec:
  selector:
    app.kubernetes.io/name: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: NodePort
